"""Shared constants for structural scoring and pruning heuristics."""

NOISE_PATH_PATTERNS = (
    "/tests/",
    "/test/",
    "/test_",
    "-test/",
    "/__tests__/",
    ".spec.",
    ".test.",
    "/docs_src/",
    "/docs/virtual/",
    "/examples/",
    "/example/",
    "/benchmarks/",
    "/types/test/",
    "/__testfixtures__/",
    "/testfixtures/",
    "/codemods/",
)
NOISE_NAME_PREFIXES = ("test_",)
NOISE_NAME_SUBSTRINGS = ("tutorial",)
NOISE_FACTOR = 0.15
EXPLORATION_NOISE_FACTOR = 0.3
LOW_SIGNAL_DOC_PATH_PATTERNS = (
    "/migrating-",
    "/comparison.",
    "/comparison.md",
    "/release-notes",
)
IMPACT_TOPIC_STOPWORDS = {
    "affected",
    "affect",
    "affects",
    "change",
    "changed",
    "changes",
    "docs",
    "documentation",
    "handling",
    "likely",
    "module",
    "modules",
    "test",
    "tests",
    "what",
    "when",
    "where",
    "which",
    "with",
}
FOCUS_QUERY_STOPWORDS = IMPACT_TOPIC_STOPWORDS | {
    "about",
    "actual",
    "assemble",
    "behavior",
    "build",
    "codebase",
    "does",
    "final",
    "flow",
    "from",
    "generate",
    "generated",
    "enhancer",
    "enhancers",
    "into",
    "logic",
    "middleware",
    "middlewares",
    "most",
    "operation",
    "parts",
    "passed",
    "returned",
    "turn",
    "user",
    "work",
}
